dist:
  trusty

language:
  c

compiler:
  gcc

env:
  global:
    - DIGRAPHS_LIB=digraphs-lib-0.5

addons:
  apt_packages:
    - g++-multilib

# Matrix
#       GAP version: |       master |  stable-4.10 | stable-4.9 |required |
#--------------------+--------------+--------------+------------+---------+
# packages:   newest | 64- & 32-bit |       64-bit |          - |       - |
# packages: required |   (coverage) |       32-bit |     64-bit |  64-bit |

# Plus: linting

matrix:
  include:
    - env:
      - SUITE=lint
      sudo:
        true
      addons:

    - env:
      - SUITE=test
      - ABI=64
      - GAP=master
      - PACKAGES=newest

    - env:
      - SUITE=test
      - ABI=32
      - GAP=master
      - PACKAGES=newest
      addons:
        apt_packages:
          - libgmp-dev:i386
          - libreadline-dev:i386
          - gcc-multilib
          - g++-multilib

    - env:
      - SUITE=test
      - ABI=64
      - GAP=stable-4.10
      - PACKAGES=newest

    - env:
      - SUITE=test
      - ABI=32
      - GAP=stable-4.10
      - PACKAGES=required
      addons:
        apt_packages:
          - libgmp-dev:i386
          - libreadline-dev:i386
          - gcc-multilib
          - g++-multilib

    - env:
      - SUITE=test
      - ABI=64
      - GAP=stable-4.9
      - PACKAGES=required

    - env:
      - SUITE=test
      - ABI=64
      - GAP=required
      - PACKAGES=required

    - env:
      - SUITE=coverage
      - ABI=64
      - GAP=master
      - PACKAGES=required
      - THRESHOLD=98

before_script:
  - export GAPROOT="$HOME/gap"
  - if [ "$ABI" == "32" ]; then export GAP_FLAGS="ABI=32 --host=i686-linux-gnu"; fi
  - if [ "$ABI" == "32" ]; then export PKG_FLAGS="CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 LOPTS=-m32 --host=i686-linux-gnu"; fi
  - scripts/travis-build-dependencies.sh

script:
  - scripts/travis-build-digraphs.sh
  - scripts/travis-test.sh
